name: Build and publish native images
on:
  push:
    branches:
      - main
      - graalvm
  pull_request:
    branches:
      - main
jobs:
  build_native_docker_image:
    name: Build and publish the native (Linux) Docker image
    runs-on: ubuntu-22.04
    env:
      DOCKER_IMAGE_NAME: 'ghcr.io/${{ env.GITHUB_ACTION_REPOSITORY }}/jhipster-lite-native'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Packages
        run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
      - name: Build application with GraalVM
        run: |
          ./mvnw -Pnative native:compile -DskipTests
      - name: Build the native (GraalVM) Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ env.DOCKER_IMAGE_NAME }}:main
          file: ./src/main/docker/Dockerfile.native
          context: .
      - name: Push to GitHub Packages
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:main
        if: ${{ github.event_name == 'push' }}
