name: Build and publish native (GraalVM) images
on:
  push:
    branches:
      - graalvm
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build_native_docker_image:
    name: Build and publish the native (GraalVM) Docker image
    runs-on: ubuntu-22.04
    env:
      DOCKER_IMAGE_NAME: '${{ github.repository }}/jhipster-lite-native'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}

      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Build application with GraalVM
        # to test the GraalVM Build using DevContainers, install GraalVM by running `sdk install java 21.0.1-graal`
        run: |
          ./mvnw -Pnative native:compile -DskipTests

      - name: Login to Docker Registry
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        if: ${{env.DOCKERHUB_USERNAME != '' && startsWith(github.ref, 'refs/tags/v')}}
        uses: docker/login-action@v3.0.0
        id: login-hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the native (GraalVM) Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./src/main/docker/Dockerfile.native
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
